use glam::Vec3;
use serde::Deserialize;

use crate::color::bv_to_rgb;
use crate::coords::{proper_motion_vector_radians_per_year, radec_hours_deg_to_cartesian};
use crate::CatalogIdentifiers;

#[derive(Debug, Deserialize)]
struct RawStar {
    id: Option<u32>,
    hip: Option<u32>,
    hd: Option<u32>,
    ra: f64,
    dec: f64,
    dist: Option<f64>,
    mag: f64,
    ci: Option<f64>,
    pmrarad: Option<f64>,
    pmdecrad: Option<f64>,
}

#[derive(Debug, Clone, Copy)]
pub struct Star {
    /// Stable catalog identifiers associated with this star when the backend
    /// can supply them. The current HYG CSV path preserves HYG / Hipparcos / HD
    /// numeric IDs; compact embedded catalogs omit IDs until Phase 3 identifier
    /// preservation is wired through the renderer.
    pub identifiers: CatalogIdentifiers,
    pub position: Vec3,
    /// Heliocentric distance in parsecs from HYG's `dist` column. Earth-centred
    /// sky rendering uses only [`Self::position`], but Phase-4 external
    /// galactic views need the same catalogue row as a 3D point in the local
    /// Milky Way neighbourhood.
    pub distance_pc: f32,
    /// Cartesian tangent vector in radians per Julian year, derived from HYG's
    /// `pmrarad` / `pmdecrad` columns. Add `proper_motion * years_since_j2000`
    /// to `position` and normalize for first-order apparent catalogue motion.
    pub proper_motion: Vec3,
    pub magnitude: f32,
    pub color: [f32; 3],
}

pub(crate) const DEFAULT_MAX_MAGNITUDE: f32 = 8.0;
/// HYG fills its `dist` (parsecs) column with the sentinel value `100000` for
/// rows where the parallax is missing, negative, or numerically meaningless.
/// We drop those rows: their on-sky position may still be fine, but using
/// them in distance-aware filtering or future 3D rendering would propagate
/// the sentinel as a real distance. Rows with no `dist` at all are kept
/// (HYG leaves the cell empty in that case). 100 kpc is far beyond the
/// stellar Milky Way disc (≈30 kpc), so no real star is filtered out by
/// this threshold.
///
/// HYG also contains the Sun (`proper=Sol`) as a synthetic row at `dist=0`,
/// `ra=0`, `dec=0`, `mag=-26.7`. It is not a background catalogue star: if
/// uploaded to the star renderer it becomes an enormous saturated PSF that
/// looks like a bogus Moon/Sun disk. Solar-system bodies must be rendered by
/// the ephemeris path instead, so non-positive distances are rejected here.
const MIN_DISTANCE_PC: f64 = 0.0;
const MAX_DISTANCE_PC: f64 = 100_000.0;
#[cfg(feature = "embedded")]
const EMBEDDED_MAGIC: &[u8; 8] = b"STRBIN3\0";
#[cfg(feature = "embedded")]
const EMBEDDED_HEADER_LEN: usize = 12;
#[cfg(feature = "embedded")]
const EMBEDDED_RECORD_LEN: usize = 26;

pub fn load_from_csv(data: &str) -> Vec<Star> {
    let mut reader = csv::ReaderBuilder::new()
        .flexible(true)
        .from_reader(data.as_bytes());

    let mut stars = Vec::new();

    for result in reader.deserialize::<RawStar>() {
        let raw = match result {
            Ok(r) => r,
            Err(e) => {
                log::warn!("Skipping malformed row: {e}");
                continue;
            }
        };

        if raw.mag > DEFAULT_MAX_MAGNITUDE as f64 {
            continue;
        }
        let distance_pc = match raw.dist {
            Some(dist) if dist > MIN_DISTANCE_PC && dist < MAX_DISTANCE_PC => dist as f32,
            Some(_) => continue,
            // Keep legacy CSV compatibility for tiny fixtures that omit HYG's
            // distance column; place them on the unit sphere for external views
            // rather than rejecting otherwise-valid sky-rendering tests.
            None => 1.0,
        };

        stars.push(Star {
            identifiers: CatalogIdentifiers::from_hyg_row(raw.id, raw.hip, raw.hd),
            position: radec_hours_deg_to_cartesian(raw.ra, raw.dec),
            distance_pc,
            proper_motion: proper_motion_vector_radians_per_year(
                raw.ra,
                raw.dec,
                raw.pmrarad.unwrap_or(0.0),
                raw.pmdecrad.unwrap_or(0.0),
            ),
            magnitude: raw.mag as f32,
            color: bv_to_rgb(raw.ci.unwrap_or(0.0) as f32),
        });
    }

    // V-54: resolve merged WDS visual doubles (Algieba, the epsilon Lyrae
    // Double Double) into their component sprites. No-op for any catalog that
    // does not contain a bootstrap primary.
    let stars = crate::doubles::resolve_doubles(stars);

    log::info!(
        "Loaded {} stars (mag <= {DEFAULT_MAX_MAGNITUDE})",
        stars.len()
    );
    stars
}

#[cfg(feature = "embedded")]
pub fn load_embedded() -> Vec<Star> {
    const DATA: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/stars.bin"));
    load_from_binary(DATA).expect("embedded compact star catalog is generated by build.rs")
}

#[cfg(feature = "embedded")]
fn load_from_binary(data: &[u8]) -> Result<Vec<Star>, String> {
    if data.len() < EMBEDDED_HEADER_LEN {
        return Err("embedded catalog is shorter than its header".to_string());
    }
    if &data[..EMBEDDED_MAGIC.len()] != EMBEDDED_MAGIC {
        return Err("embedded catalog has an unknown magic header".to_string());
    }

    let count = u32::from_le_bytes(data[8..12].try_into().expect("fixed-size count")) as usize;
    let expected_len = EMBEDDED_HEADER_LEN + count * EMBEDDED_RECORD_LEN;
    if data.len() != expected_len {
        return Err(format!(
            "embedded catalog length mismatch: expected {expected_len} bytes, got {}",
            data.len()
        ));
    }

    let mut stars = Vec::with_capacity(count);
    for record in data[EMBEDDED_HEADER_LEN..].chunks_exact(EMBEDDED_RECORD_LEN) {
        let x = decode_unit_i16(record, 0);
        let y = decode_unit_i16(record, 2);
        let z = decode_unit_i16(record, 4);
        let magnitude = decode_i16(record, 6) as f32 / 100.0;
        let ci = decode_i16(record, 8) as f32 / 1000.0;
        let proper_motion = Vec3::new(
            decode_f32(record, 10),
            decode_f32(record, 14),
            decode_f32(record, 18),
        );
        let distance_pc = decode_f32(record, 22);
        stars.push(Star {
            identifiers: CatalogIdentifiers::default(),
            position: Vec3::new(x, y, z).normalize_or_zero(),
            distance_pc,
            proper_motion,
            magnitude,
            color: bv_to_rgb(ci),
        });
    }

    // V-54: resolve merged WDS visual doubles on the embedded path too. The
    // compact binary drops identifiers, so the resolver matches primaries by
    // position.
    let stars = crate::doubles::resolve_doubles(stars);

    log::info!("Loaded {} embedded stars (compact binary)", stars.len());
    Ok(stars)
}

#[cfg(feature = "embedded")]
fn decode_i16(record: &[u8], offset: usize) -> i16 {
    i16::from_le_bytes(
        record[offset..offset + 2]
            .try_into()
            .expect("fixed-size field"),
    )
}

#[cfg(feature = "embedded")]
fn decode_unit_i16(record: &[u8], offset: usize) -> f32 {
    decode_i16(record, offset) as f32 / i16::MAX as f32
}

#[cfg(feature = "embedded")]
fn decode_f32(record: &[u8], offset: usize) -> f32 {
    f32::from_le_bytes(
        record[offset..offset + 4]
            .try_into()
            .expect("fixed-size field"),
    )
}

#[cfg(feature = "filesystem")]
pub fn load_from_file(path: impl AsRef<std::path::Path>) -> std::io::Result<Vec<Star>> {
    use crate::{CatalogBackend, CatalogError, CatalogQuery, HygCsvBackend};

    let backend = HygCsvBackend::new(path.as_ref().to_path_buf());
    backend
        .load(CatalogQuery::default())
        .map(|page| page.stars)
        .map_err(|error| match error {
            CatalogError::Io(error) => error,
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    const HEADER: &str = "id,hip,hd,hr,gl,bf,proper,ra,dec,dist,pmra,pmdec,rv,mag,absmag,spect,ci,x,y,z,vx,vy,vz,rarad,decrad,pmrarad,pmdecrad,bayer,flam,con,comp,comp_primary,base,lum,var,var_min,var_max";

    #[test]
    fn loads_a_star() {
        let csv = format!(
            "{HEADER}\n1,1,224700,,,,Sirius,6.752477,16.716116,2.637,0.0,0.0,0.0,-1.46,1.45,A1V,-0.01,0,0,0,0,0,0,0,0,0,0,,,Psc,1,1,,1.0,,,\n"
        );
        let stars = load_from_csv(&csv);
        assert_eq!(stars.len(), 1);
        assert_eq!(stars[0].identifiers.hyg, Some(1));
        assert_eq!(stars[0].identifiers.hip, Some(1));
        assert_eq!(stars[0].identifiers.hd, Some(224700));
        assert!((stars[0].magnitude - (-1.46)).abs() < 0.01);
        assert!((stars[0].distance_pc - 2.637).abs() < 0.001);
        assert!(stars[0].position.length() > 0.99);
        assert_eq!(stars[0].proper_motion, Vec3::ZERO);
    }

    #[test]
    fn filters_dim_stars() {
        let csv = format!(
            "{HEADER}\n\
             1,1,,,,,Star1,0.0,0.0,10.0,0.0,0.0,0.0,5.0,0.0,G2V,0.0,0,0,0,0,0,0,0,0,0,0,,,Psc,1,1,,1.0,,,\n\
             2,2,,,,,Star2,0.0,0.0,10.0,0.0,0.0,0.0,9.0,0.0,G2V,0.0,0,0,0,0,0,0,0,0,0,0,,,Psc,1,1,,1.0,,,\n"
        );
        let stars = load_from_csv(&csv);
        assert_eq!(
            stars.len(),
            1,
            "should filter mag > {DEFAULT_MAX_MAGNITUDE}"
        );
    }

    #[test]
    fn filters_synthetic_sun_row() {
        let csv = format!(
            "{HEADER}\n\
             0,,,,,,Sol,0.0,0.0,0.0,0.0,0.0,0.0,-26.7,4.85,G2V,0.656,0,0,0,0,0,0,0,0,0,0,,,Ori,1,1,,1.0,,,\n\
             1,1,,,,,Sirius,6.752477,-16.716116,2.637,0.0,0.0,0.0,-1.46,1.45,A1V,-0.01,0,0,0,0,0,0,0,0,0,0,,,CMa,1,1,,1.0,,,\n"
        );
        let stars = load_from_csv(&csv);
        assert_eq!(stars.len(), 1, "the Sun is not a catalogue star");
        assert!((stars[0].magnitude - (-1.46)).abs() < 0.01);
    }
}
