use std::{env, fs, path::Path};

const TABLES: &[(&str, &str, &str)] = &[
    (
        "data/constellation_boundaries.csv",
        "constellation_boundaries.rs",
        "CONSTELLATION_BOUNDARY_SEGMENTS",
    ),
    (
        "data/constellation_lines.csv",
        "constellation_lines.rs",
        "CONSTELLATION_LINE_SEGMENTS",
    ),
];

fn main() {
    for (input, output, symbol) in TABLES {
        println!("cargo:rerun-if-changed={input}");
        generate_table(input, output, symbol);
    }
}

fn generate_table(input: &str, output: &str, symbol: &str) {
    let rows = read_segments(input);
    let mut generated = String::new();
    generated.push_str("// Generated by crates/renderer/build.rs from ");
    generated.push_str(input);
    generated.push_str(".\n");
    generated.push_str("// Each row is two J2000 unit vectors: [x0, y0, z0, x1, y1, z1].\n");
    generated.push_str("#[allow(clippy::excessive_precision)]\n");
    generated.push_str(&format!(
        "pub static {symbol}: [[f32; 6]; {}] = [\n",
        rows.len()
    ));
    for row in rows {
        generated.push_str(&format!(
            "    [{:.8e}, {:.8e}, {:.8e}, {:.8e}, {:.8e}, {:.8e}],\n",
            row[0], row[1], row[2], row[3], row[4], row[5]
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR for build scripts");
    fs::write(Path::new(&out_dir).join(output), generated)
        .expect("write generated constellation table");
}

fn read_segments(input: &str) -> Vec<[f32; 6]> {
    let text = fs::read_to_string(input).expect("read constellation data table");
    let mut rows = Vec::new();
    for (line_number, line) in text.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("x0,") {
            continue;
        }
        let mut row = [0.0_f32; 6];
        let mut count = 0;
        for (slot, field) in row.iter_mut().zip(trimmed.split(',')) {
            *slot = field
                .trim()
                .parse::<f32>()
                .unwrap_or_else(|_| panic!("invalid float in {input} at line {}", line_number + 1));
            count += 1;
        }
        if count != 6 || trimmed.split(',').count() != 6 {
            panic!(
                "expected 6 comma-separated fields in {input} at line {}",
                line_number + 1
            );
        }
        assert_unit_vector(input, line_number + 1, &row[0..3]);
        assert_unit_vector(input, line_number + 1, &row[3..6]);
        rows.push(row);
    }
    if rows.is_empty() {
        panic!("{input} contains no constellation segments");
    }
    rows
}

fn assert_unit_vector(input: &str, line_number: usize, v: &[f32]) {
    let length = (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt();
    assert!(
        length.is_finite() && (length - 1.0).abs() < 1.0e-4,
        "non-unit vector in {input} at line {line_number}: length={length}"
    );
}
