#!/bin/bash
# Regenerate the curated V-55 satellite TLE snapshot from CelesTrak.
#
# The default render path ships the committed snapshot at
# crates/common/data/satellites/curated_tle.txt for deterministic renders;
# this script refreshes it. Re-run `make manifest-check` afterwards and update
# the sha256 / retrieved date in data/manifest.toml + DATA_SOURCES.md.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="crates/common/data/satellites/curated_tle.txt"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Curated representative set: ISS, a bright LEO (Hubble), a polar LEO
# (NOAA-20), a Starlink train member, and a geostationary-belt member (GOES-16).
CATNRS=(25544 20580 43013 44714 41866)

BASE="https://celestrak.org/NORAD/elements/gp.php"

{
  echo "# Curated artificial-satellite TLE snapshot for the V-55 satellite layer."
  echo "# Regenerated by scripts/fetch-satellite-tle.sh from CelesTrak GP service."
  echo "# Retrieved: $(date -u +%Y-%m-%d). License: US Space Force public domain (see DATA_SOURCES.md)."
} > "$TMP"

for n in "${CATNRS[@]}"; do
  curl -fsS -o /tmp/_tle_$n.txt "${BASE}?CATNR=${n}&FORMAT=tle"
  # Trim trailing whitespace from the name line and append the 3-line block.
  sed -e 's/[[:space:]]*$//' /tmp/_tle_$n.txt >> "$TMP"
  rm -f /tmp/_tle_$n.txt
done

mv "$TMP" "$OUT"
trap - EXIT
echo "Wrote $(grep -c '^[12] ' "$OUT") TLE lines to $OUT"
echo "Now refresh data/manifest.toml sha256 + DATA_SOURCES.md, then run: make manifest-check"
